export const ERROR_CODES = {
  CONCURRENT_WRITE: "CONCURRENT_WRITE",
  DOCUMENT_ALREADY_EXISTS: "DOCUMENT_ALREADY_EXISTS",
  DOCUMENT_NOT_FOUND: "DOCUMENT_NOT_FOUND",
  DOCUMENT_VERSION_AHEAD_OF_SCHEMA: "DOCUMENT_VERSION_AHEAD_OF_SCHEMA",
  DUPLICATE_BATCH_SET_KEYS: "DUPLICATE_BATCH_SET_KEYS",
  ENGINE_DOCUMENT_ALREADY_EXISTS: "ENGINE_DOCUMENT_ALREADY_EXISTS",
  ENGINE_DOCUMENT_NOT_FOUND: "ENGINE_DOCUMENT_NOT_FOUND",
  ENGINE_UNIQUE_CONSTRAINT_VIOLATION: "ENGINE_UNIQUE_CONSTRAINT_VIOLATION",
  MIGRATION_ALREADY_RUNNING: "MIGRATION_ALREADY_RUNNING",
  MIGRATION_FUNCTION_MISSING: "MIGRATION_FUNCTION_MISSING",
  MIGRATION_PROJECTION_FAILED: "MIGRATION_PROJECTION_FAILED",
  MIGRATION_SCOPE_CONFLICT: "MIGRATION_SCOPE_CONFLICT",
  MISSING_MIGRATOR: "MISSING_MIGRATOR",
  UNIQUE_CONSTRAINT_VIOLATION: "UNIQUE_CONSTRAINT_VIOLATION",
  VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export interface CodedError {
  readonly code: ErrorCode;
}

export abstract class NosqlOdmError<TCode extends ErrorCode> extends Error implements CodedError {
  readonly code: TCode;

  protected constructor(name: string, code: TCode, message: string) {
    super(message);
    this.name = name;
    this.code = code;
  }
}
