export { ERROR_CODES, type CodedError, type ErrorCode, NosqlOdmError } from "./errors";

export {
  model,
  type ModelDefinition,
  ValidationError,
  VersionError,
  MigrationError,
  type MigrationStrategy,
  type MigrationErrorMode,
  type ModelOptions,
  type SchemaOptions,
  type VersionValue,
  type ParseVersion,
  type CompareVersions,
  type ProjectionSkipReason,
  type ProjectionResult,
  compareSemverVersions,
  encodeNumericIndexValue,
  type IndexValue,
  type IndexDefinition,
  type DynamicIndexDefinition,
  type Model,
  type ModelBuilder,
  type InitialModelBuilder,
  parseSemverVersion,
} from "./model";

export {
  createStore,
  ConcurrentWriteError,
  DocumentAlreadyExistsError,
  DocumentNotFoundError,
  DuplicateBatchSetKeysError,
  MigrationProjectionError,
  MigrationAlreadyRunningError,
  MissingMigratorError,
  MigrationScopeConflictError,
  UniqueConstraintError,
  type QueryResult,
  type BatchSetInputItem,
  type DuplicateBatchSetKeyConflict,
  type MigrationResult,
  type MigrationSkipReasons,
  type MigrationModelTelemetry,
  type MigrationRunOptions,
  type MigrationRunProgress,
  type MigrationNextPageResult,
  type MigrationPageTelemetry,
  type CreateStoreOptions,
  type UniqueConstraintLockOptions,
  type Migrator,
  type MigrationHooks,
  type BoundModel,
  type Store,
} from "./store";

export { DefaultMigrator } from "./migrator";

export {
  EngineDocumentAlreadyExistsError,
  EngineDocumentNotFoundError,
  EngineUniqueConstraintError,
} from "./engines/types";

export type {
  ComparableVersion,
  ResolvedIndexKeys,
  BatchSetItem,
  EngineGetResult,
  FieldCondition,
  QueryFilter,
  WhereFilter,
  QueryParams,
  KeyedDocument,
  EngineQueryResult,
  UniqueProbeMatch,
  MigrationLock,
  AcquireLockOptions,
  MigrationCriteria,
  MigrationStatus,
  QueryEngine,
} from "./engines/types";
