export {
  model,
  type ModelDefinition,
  ValidationError,
  VersionError,
  MigrationError,
  type MigrationStrategy,
  type MigrationErrorMode,
  type ModelOptions,
  type SchemaOptions,
  type VersionValue,
  type ParseVersion,
  type CompareVersions,
  type ProjectionSkipReason,
  type ProjectionResult,
  encodeNumericIndexValue,
  type IndexValue,
  type IndexDefinition,
  type DynamicIndexDefinition,
  type Model,
  type ModelBuilder,
  type InitialModelBuilder,
} from "./model";

export {
  createStore,
  DocumentAlreadyExistsError,
  DocumentNotFoundError,
  MigrationProjectionError,
  MigrationAlreadyRunningError,
  MissingMigratorError,
  MigrationScopeConflictError,
  UniqueConstraintError,
  type QueryResult,
  type BatchSetInputItem,
  type MigrationResult,
  type MigrationSkipReasons,
  type MigrationRunOptions,
  type MigrationRunProgress,
  type MigrationNextPageResult,
  type CreateStoreOptions,
  type UniqueConstraintLockOptions,
  type Migrator,
  type MigrationHooks,
  type BoundModel,
  type Store,
} from "./store";

export { DefaultMigrator } from "./migrator";

export {
  EngineDocumentAlreadyExistsError,
  EngineDocumentNotFoundError,
  EngineUniqueConstraintError,
} from "./engines/types";

export type {
  ComparableVersion,
  ResolvedIndexKeys,
  BatchSetItem,
  EngineGetResult,
  FieldCondition,
  QueryFilter,
  WhereFilter,
  QueryParams,
  KeyedDocument,
  EngineQueryResult,
  MigrationLock,
  AcquireLockOptions,
  MigrationCriteria,
  MigrationStatus,
  QueryEngine,
} from "./engines/types";
